// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR-qEazIR1AfJSM_6jwPMuGlzPKtXwAgw',
    appId: '1:769449547886:web:eb8ff9540c86fb32106e7f',
    messagingSenderId: '769449547886',
    projectId: 'chatting-42e44',
    authDomain: 'chatting-42e44.firebaseapp.com',
    storageBucket: 'chatting-42e44.appspot.com',
    measurementId: 'G-PE96FXSF7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGUo7Jrx_r97AVu_PX_i4C-1FArpqaoE',
    appId: '1:769449547886:android:75a1b5bc1c8fe8bb106e7f',
    messagingSenderId: '769449547886',
    projectId: 'chatting-42e44',
    storageBucket: 'chatting-42e44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Y3s0RbtyDeHJ8tIC77stgd3qU89MyEQ',
    appId: '1:769449547886:ios:c0fdaf00a53efac3106e7f',
    messagingSenderId: '769449547886',
    projectId: 'chatting-42e44',
    storageBucket: 'chatting-42e44.appspot.com',
    iosClientId: '769449547886-8lehgb4tru9kkkj7nvom77i3ah0anhan.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Y3s0RbtyDeHJ8tIC77stgd3qU89MyEQ',
    appId: '1:769449547886:ios:c0fdaf00a53efac3106e7f',
    messagingSenderId: '769449547886',
    projectId: 'chatting-42e44',
    storageBucket: 'chatting-42e44.appspot.com',
    iosClientId: '769449547886-8lehgb4tru9kkkj7nvom77i3ah0anhan.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatting',
  );
}
